### PR TITLE
WDM timeline plot

### PR DESCRIPTION
**Pull request by kadrlica**
Here is a timeline of WDM constraints that I created for an overview talk. 

Data are located in `wdm_timeline.yaml` in case you want to make your own plot!

image

### CODE REVIEW

**Comment by eonadler** [comment]
Sorry for the long delay in reviewing! This is an awesome and extremely helpful plot. I have a few practical suggestions for the plot and a few "meta" comments.

Pracical suggestions:

- Here are some other Lyman-alpha limits to consider adding: Narayanan+00 (https://arxiv.org/abs/astro-ph/0005095), Viel+07 (https://link.springer.com/chapter/10.1007/978-88-470-0747-5_40), Viel+13 (https://arxiv.org/abs/1306.2314), Baur+16 (https://arxiv.org/abs/1512.01981), Garzilli+21 (https://academic.oup.com/mnras/article-abstract/502/2/2356/6117414?redirectedFrom=fulltext).

- Here are some other dwarf galaxy references to consider adding: Maccio & Fontanot 2010 (https://arxiv.org/abs/0910.2460), Newton+20 (https://arxiv.org/abs/2011.08865).

- We might consider adding Schneider+16 (https://arxiv.org/abs/1601.07553) to both the Lyman-alpha and dwarf galaxy sets, but this would take some sterile neutrino --> thermal relic mapping.

- On the stream constraints, I think it is also worth including Banik+21 (https://arxiv.org/abs/1911.02662) in the .yaml and differentiating a few of the limits reported there with those from Banik+19 (https://arxiv.org/abs/1911.02663). In particular, Banik+21 Section 4.1 reports m_wdm > 4.6 keV (consistent with the limit quoted in Banik+19) if the amplitude and slope of the mass function are fixed and if only GD-1 is included in the datavector; the constraint weakens if Pal-5 is included. Section 4.2 frees the SHMF amplitude and slope, yielding m_wdm > 3 keV from GD-1 alone and no strong constraint from GD-1 + Pal-5. I bring this up because, in other cases, I think this plot reports the most conservative limits from each paper, discussed more below. This isn't an issue because the streams point isn't plotted for now, but eventually I'm sure we want to include it.

- For the "Combinations," it would be great to mark each purple arrow with a distinct symbol and to mark the constraints it combined with the same symbol (e.g., Nadler+21b, Gilman+19, and Nadler+21a could all be marked with stars). This would make the correlation between various results more clear. Also, the Enzi+21 limit changed from 6.7 to 6.0 keV: https://arxiv.org/abs/2010.13802v3.

Meta comments:

- What do we mean by "Combinations"? As an example, Viel+06 and Seljak+06 include CMB and galaxy power spectrum data in their fits. Unfortunately, they don't present a limit for Lyman-alpha only, although Seljak+06 comments that "While galaxy clustering and CMB data do not constrain WDM, they are useful for constraining the remaining cosmological parameters." I'm in favor of labeling these "Lyman-alpha" instead of "Combinations," since all of the limits in the plot are "Combinations" in this way. But at some point it might be helpful to define what "Combinations" means. Something like "the use of two independent datasets that individually set non-negligible WDM constraints," where we need to quantitatively define "independent" and "non-negligible."

- For the "individual" limits, I wonder if we can/should make a version of the plot that explicitly shows which results use the same data. This might help indicate the size of systematic uncertainties between various models.

- Should we only indicate the most conservative limits from each paper? This is reasonable for making an easily readable version of the plot, but showing the reported spread from each analysis in another version might be helpful to indicate the relative size of systematic uncertainties in each model.

**Comment by kadrlica** [comment]
Awesome comments, thanks @eonadler! 

I'll try to work through these, but I'd of course appreciate any PR that you have time to make.

One quick response to one of your comments: I am actually trying to store **all** the limits that come from each paper. Logistically, this means storing a list of `mwdm` constraint values in the yaml file. For example:
```
I17:
  author: 'Irsic+17'
  date: '2017-07-19'
  mwdm: [3.5, 5.3]
  type: 'lya'
  ref: '1702.01764'
```
In the figure, these are shown as a solid + dashed arrow (I admit this may not be the clearest visualization).

**Comment by kadrlica** [comment]
Ok, I think I've included each of the additional references suggested above except for Schneider+16, which needs conversion ([Cherry & Horiuchi 2017](https://arxiv.org/abs/1701.07874) is a similar situation). New version of the figure posted below.

image

**Comment by eonadler** [comment]
This looks great. The other changes aren't important so I think we should merge this soon. Before doing so, I wanted to bring up including the high-z galaxy luminosity function as a distinct probe on the plot. For example, Pacucci+13 (https://arxiv.org/abs/1306.0009), Corasaniti+17 (https://arxiv.org/abs/1611.05892). If we go for this I can compile a more complete list of references.

**Comment by eonadler** [comment]
Thanks for adding these! Here are a few more high-z references: Schultz+14 (https://arxiv.org/abs/1401.3769), Menci+16 (https://arxiv.org/abs/1601.01820), Rudakovskyi+21 (https://arxiv.org/abs/2104.04481). I'm thinking these would be helpful to include on the plot.

**Comment by kadrlica** [comment]
I've added those high-z galaxy references, and I've added both the high-z galaxies and stellar streams to the figure. It should be fairly easy for users to turn on and off the various probes if they want to remake this figure.

image

**Comment by eonadler** [comment]
Looks good -- this is a great figure! 🙌

**Review by eonadler — COMMENTED** [review]
Looks good!

**Review by eonadler — APPROVED** [review]
Looks good!

**Pull request merged**
